# Set language to R:
language: r

# Make sudo required (I guess this helps with some issues):
sudo: required

# Make sure dependencies are available:
before_install:
  - sudo apt-get -y install  libglu1-mesa-dev

# Addons
addons:
  apt:
    packages:
      - libgsl2
      - gsl-bin
      - libgsl-dev
      - libmagick++-dev

# Adding lintr to checks:
r_github_packages:
  - jimhester/lintr

# Be strict when checking our package
warnings_are_errors: true

# r_check_args: --as-cran --run-donttest 

# for code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

