#
addons:
  apt:
    packages:
      - libgsl2
      - gsl-bin
      - libgsl-dev
      - libmagick++-dev

language: r
sudo: required

before_install:
  - apt-get install libglu1-mesa-dev

##because of phangorn
#bioc_packages: 
#   - Biostrings

# Be strict when checking our package
warnings_are_errors: true

# r_check_args: --as-cran --run-donttest 

# for code coverage
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

